# Build only on MR or main branches
.only-default: &only-default
  only:
    - main
    - merge_requests
  tags:
    - V100

stages:
  - test

test:bignlp_hp_tool:
  <<: *only-default
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install 'pytest>=3'
    - export PATH="/home/gitlab-runner/.local/bin:$PATH"
    - pytest tests
