variables: &VARS
  BIGNLP_REGISTRY: "gitlab-master.nvidia.com:5005/dl/joc/bignlp-scripts"
  BIGNLP_BUILD_PATH: "/lustre/fsw/joc/yuya/bignlp/bignlp-scripts_ci"
  BIGNLP_BASE_IMAGE: "gitlab-master.nvidia.com:5005/dl/dgx/bignlp/train:22.04-py3-base"

stages:
  - build
  - test
  - upload_results

################
# JOB Templates
################

test:unit_tests:
  tags:
    - V100
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pip install requests-mock
    - export PATH="/home/gitlab-runner/.local/bin:$PATH"
    - pytest tests/unit_tests
  rules:
    - when: always

before_script:
  - export DOCKERFILE=./Dockerfile
  - if [[ -z ${BASE_IMAGE} ]]; then
    export BASE_IMAGE=$(grep -oP "ARG FROM_IMAGE_NAME=\K\S+" ${DOCKERFILE});
    else
    export FROM_IMAGE_NAME=$BASE_IMAGE;
    fi
  - export IMAGE_NAME=${BASE_IMAGE##*/}
  - export IMAGE_NAME=${IMAGE_NAME%:*}
  - export BUILD_IMAGE_NAME=${BIGNLP_REGISTRY}/${IMAGE_NAME}:pipe.${CI_PIPELINE_ID}
  - export BUILD_IMAGE_NAME_SRUN="${BUILD_IMAGE_NAME/:5005\//#}"

.build: &build_template
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN "${CI_REGISTRY}"
    - export DOCKER_REGISTRY="${CI_REGISTRY/:5005/}"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN "${DOCKER_REGISTRY}"
    # Define bignlp build image
    - set -x
    - ls
    - env
    - export FROM_IMAGE_ARG="--build-arg FROM_IMAGE_NAME=${BASE_IMAGE}"
    - docker build -t ${BUILD_IMAGE_NAME} ${FROM_IMAGE_ARG} .
    - docker push ${BUILD_IMAGE_NAME}
  allow_failure: false
  tags:
    - vm-builder

.LUNA: &LUNA
  variables: &LUNA_VARS
    SLURM_PARTITION: "luna"
    SLURM_NIGHTLY_PARTITION: "luna"
    SLURM_ACCOUNT: "joc"
    GPFSFOLDER:    "/lustre/fsw/$SLURM_ACCOUNT"
    CLUSTER:       "selene"
    PYXIS_LITE:    "1"
    ENROOT_MOUNT_HOME: "n"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$SLURM_ACCOUNT/$CI_CONCURRENT_ID/$CI_PROJECT_NAME # THIS DOES NOT HAVE QUOTES FOR A REASON
    EXCLUDE_NODES: ""
    GPU_ARCH:      "A100"
    NUM_NODES:     1
  tags: &LUNA_TAGS
    - selene_ssh

build-BigNLP:
  <<: *build_template

gpt3.126m_short:
  tags: *LUNA_TAGS
  stage: test
  variables:
    <<: [*VARS, *LUNA_VARS]
  script:
    - set -x
    - rm -rf /lustre/fsw/joc/big_nlp/bignlp_ci/results/*
    - source /lustre/fsw/joc/big_nlp/nemo_gpt3/my_venv/bin/activate
    - export RESULTS_DIR=/lustre/fsw/joc/big_nlp/bignlp_ci/results
    - export MODEL_RESULTS_DIR=${RESULTS_DIR}/ci_gpt3_126m_deterministic
    - pwd
    - bash tests/ci_tests/launch_selene_gpt3_126m.sh
    # Wait for job to launch
    - sleep 10s # Without this, "sacct" in jobstate.sh does not always find the SLURM job.
    - export SLURM_JOBID=$(grep 'Submitted batch job' "${MODEL_RESULTS_DIR}/launcher.log" | awk '{ print $4 }')
    - echo $SLURM_JOBID
    - export SLURM_OUTPUT=$(scontrol show job "${SLURM_JOBID}" | grep 'StdOut' | awk -F '=' '{ print $2 }')
    - cd tests/ci_tests/utils
    - ./jobwait.sh "${SLURM_JOBID}" & PID=$!
    - touch "${SLURM_OUTPUT}"
    - echo -e " ---------------------------------------------------\n"
                "----------WAITING FOR SLURM JOB TO BEGIN-----------\n"
                "---------------------------------------------------\n"
                "$(scontrol show job=${SLURM_JOBID})\n"
                "---------------------------------------------------\n"
    # Gitlab logs collapsible section markers
    - echo -e "\e[0Ksection_end:`date +%s`:slurm_setup\r\e[0K"
    # Follow output of the job
    - tail --pid="${PID}" -f "${SLURM_OUTPUT}" # Stream job output until it finishes.
    - echo "Finished GPT-3 126M training job"
    # Run Pytest
    - pip3 install pytest
    - pytest tests/ci_tests/test_ci_gpt3_126m.py
    - echo "Finished pytest job"
  rules:
    - when: always
  needs:
    - build-BigNLP
