run:
  name: ${.task_name}_${.model_train_name}
  time_limit: "1-12:00:00"
  dependency: "singleton"
  convert_name: convert_nemo
  model_train_name: t5_220m
  eval_name: "eval_mnli"  # supported: ???
  results_dir: ${base_results_dir}/${.model_train_name}/${.eval_name}

trainer:
  gpus: 8
  num_nodes: 1
  accelerator: ddp
  precision: 16
  logger: False # logger provided by exp_manager
  checkpoint_callback: False
  replace_sampler_ddp: False
  max_epochs: 4
  max_steps: null # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 10
  val_check_interval: 500
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: ${evaluation.run.results_dir}
  exp_dir: null
  name: megatron_t5_glue
  create_checkpoint_callback: False

model:
  restore_from_path: ???.nemo # Path to a trained T5 .nemo file
  tensor_model_parallel_size: 1

  data:
    validation_ds:
      task_name: ${evaluation.run.task_name}
      file_path: ${data_dir}/MNLI/dev_matched.tsv # Path to the TSV file for MNLI dev ex: '/raid/Data/GLUE/MNLI/dev_matched.tsv'
      batch_size: 16
      shuffle: False
      num_workers: 4
      pin_memory: True
      max_seq_length: 512

