defaults:
  - _self_
  - cluster: bcm
  - search_config: 126m
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

bignlp_hp_tool_path: /lustre/fsw/joc/big_nlp/nemo_gpt3/hp_tool/bignlp-hp-tool  # Path should end with bignlp-hp-tool
base_results_dir: ${bignlp_hp_tool_path}/results
data_dir: /lustre/fsw/joc/big_nlp/gpt3/prepare_dataset/the_pile/train

training_container: nvcr.io/nvidian/bignlp-training:22.02.05-py
container_mounts:
    - null
