defaults:
  - _self_
  - data_preparation: download_pile
  - training: 126m  # Must match training_config below.
  - conversion: convert
  - evaluation: evaluate_all
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

run_data_preparation: False
run_training: True
run_conversion: False
run_evaluation: False

cluster_type: bcm  # bcm or bcp
training_config: 126m  # Must match - training above.
bignlp_path: /workspace-scripts/bignlp-scripts # Path should end with bignlp-scripts
data_dir: /workspace-common/data/the_pile  # Location to store and read the data. Absolute or relative
container_mounts: # List of additional paths to mount to container. They will be mounted to same path.
  - null
container: nvcr.io/ea-bignlp/bignlp-training:21.12-py3
code_dir: /opt/bignlp/NeMo
