defaults:
  - _self_
  - data_preparation: download_pile
  - training: 126m
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

bignlp_path: ??? # Path to where the bignlp-scripts repo is. Should end with /.../bignlp-scripts
container: gitlab-master.nvidia.com/dl/dgx/bignlp:21.10.02-py3-base
