defaults:
  - _self_
  - cluster: bcm  # Must match custer_type below.
  - data_preparation: download_pile
  - training: 5b  # Must match training_config below.
  - conversion: convert
  - evaluation: evaluate_all
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

run_data_preparation: True
run_training: True
run_conversion: True
run_evaluation: True

cluster_type: bcm  # bcm or bcp. Must match - cluster above.
training_config: 5b  # Must match - training above.
bignlp_path: ???  # Path should end with bignlp-scripts
data_dir: ${bignlp_path}/data  # Location to store and read the data.
base_results_dir: ${bignlp_path}/results  # Location to store the results, checkpoints and logs.
container_mounts: # List of additional paths to mount to container. They will be mounted to same path.
  - null
container: nvcr.io/nvidian/swdl/bignlp:22.01.01-py3-base

wandb_api_key_file: null  # File where the w&B api key is stored. Key must be on the first line.
nccl_topology_xml_file: null  # This file will be exported as "export NCCL_TOPO_FILE=${nccl_topology_xml_file}"
