defaults:
  - _self_
  - data_preparation: download_pile
  - training: 5b # Must match training_config below.
  - evaluation: evaluate_lambada
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

run_data_preparation: False
run_training: True
run_evaluation: False

training_config: 5b  # Must match - training above.
bignlp_path: /workspace-common/bignlp-scripts # Path to where the bignlp-scripts repo is. Should end with /.../bignlp-scripts
data_dir: ${bignlp_path}/data_preparation/data  # Location to store and read the data. Absolute or relative
container_mounts: # List of additional paths to mount to the container. They will be mounted to the same path.
  - null
container: nvcr.io/ea-bignlp/bignlp-training:21.10-py3-base
code_dir: /opt/bignlp/NeMo # or /workspace-common/NeMo
