defaults:
  - _self_
  - data_preparation: download_pile
  - training: 126m
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

bignlp_path: "/gpfs/fs1/mausin/bignlp-scripts"
