defaults:
  - _self_
  - data_preparation: download_pile
  - training: 5b  # Must match training_config below.
  - conversion: convert
  - evaluation: evaluate_all
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

run_data_preparation: True
run_training: True
run_conversion: True
run_evaluation: True

training_config: 5b  # Must match - training above.
bignlp_path: ??? # Path to where the bignlp-scripts repo is. Should end with /.../bignlp-scripts
data_dir: ${bignlp_path}/data_preparation/data  # Location to store and read the data. Absolute or relative
container_mounts: # List of additional paths to mount to the container. They will be mounted to the same path.
  - null
container: nvcr.io/ea-bignlp/bignlp-training:21.10-py3-base
