defaults:
  - _self_
  - cluster: bcm
  - search_config: t5/2.8b
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

run_training_hp_search: True
run_inference_hp_search: True

bignlp_hp_tool_path: /lustre/fsw/joc/big_nlp/nemo_gpt3/hp_tool/bignlp-hp-tool  # Path should end with bignlp-hp-tool.
bignlp_inference_path: ${bignlp_hp_tool_path}/../BigNLP-Inference-Scripts  # Path to the location of BigNLP-Inference-Scripts codebase.
base_results_dir: ${bignlp_hp_tool_path}/results
data_dir: /lustre/fsw/joc/big_nlp/t5/dataset/Pile

training_container: nvcr.io/nvidian/bignlp-training:22.04.08-py
container_mounts:
    - null

wandb:  # Weights and Biases (W&B) logging.
    enable: True  # Whether to save logs to W&B.
    api_key_file: ${bignlp_hp_tool_path}/api_key.txt  # Path to the file where the w&B api key is stored. Key must be on the first line.
    project: bignlp-hp-tool  # Name of the W&B project to store the logs in. The name of the run will be populated automatically.

# Do not modify the code below.
search_config_value: ${hydra:runtime.choices.search_config}
