name: unit_tests

on:
  push:
    branches:
      - 'dpykhtar/unit_tests'
  pull_request:
    branches:
      - 'dpykhtar/unit_tests'

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Pytest
        run: python -m pip install pytest
      - name: Run Unit Tests
        run: cd ../../launcher_scripts
        run: pytest