name: unit_tests

on:
  pull_request:
    branches:
      - 'dpykhtar/unit_tests'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./launcher_scripts

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install pytest
        run: python -m pip install pytest

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests-mock

      - name: run unit tests
        run: pytest
        working-directory: ${{env.working-directory}}